[package]
name = "blockchain-in-rust"
version = "0.1.0"
authors = ["Clinton Bugtong <clintbugs.dev@gmail.com>"]
edition = "2018"

[lib]
name = "blockchainlib"
path = "src/lib.rs"

[[bin]]
name = "blockchain"
path = "src/main.rs"

[dependencies]
hex = "0.4"
crypto-hash = "0.3.4"